In [1]:
# ELEC6604 Assignment 3B demo python file

In [9]:
# PART 1: 
# CONNECT WITH YOUR DRIVE IF IN COLAB

mode = 'jupyter'  # mode = 'colab'  or 'jupyter'

if mode == 'colab' :
    from google.colab import drive
    drive.mount('/content/drive')

In [15]:
# LOAD IN THE LIBRARIES
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical

if mode == 'colab' :
    # for Colab: keras imports for the dataset and building our neural network
    from keras.datasets import cifar10
    from keras.models import Sequential
    from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
    from keras.utils import np_utils

# for Jupyter notebook, you have to import the necessary library
# .....


In [11]:
# PART 2A: THE FOLLOWING IS ONLY FOR jupyter notebook RUNNING
# loading the dataset directly from Internet
if mode == 'jupyter' :
    from tensorflow.keras.datasets import cifar10
    (X_train, y_train), (X_test, y_test) = cifar10.load_data()

    print('X_train.shape is ', X_train.shape)
    print('y_train.shape is ', y_train.shape)
    print('X_test.shape is ', X_test.shape)
    print('y_test.shape is ', y_test.shape)


X_train.shape is  (50000, 32, 32, 3)
y_train.shape is  (50000, 1)
X_test.shape is  (10000, 32, 32, 3)
y_test.shape is  (10000, 1)


In [6]:
# PART 2B: 
# THE FOLLOWING IS FOR RUNNING in Colab with the directory of dataset ready

In [7]:
# for Colab use
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [ ]:
# for Colab use
batch_names = unpickle('/content/drive/MyDrive/ELEC6604_Sept2022/Class6_7_folder/cifar-10-batches-py/batches.meta')

print(batch_names)
for x in batch_names:
  print('print x:',x)

print('')
image_label_names = batch_names[b'label_names']
print('image_label_names are ',image_label_names)
print(image_label_names[0])


{b'num_cases_per_batch': 10000, b'label_names': [b'airplane', b'automobile', b'bird', b'cat', b'deer', b'dog', b'frog', b'horse', b'ship', b'truck'], b'num_vis': 3072}
print x: b'num_cases_per_batch'
print x: b'label_names'
print x: b'num_vis'

image_label_names are  [b'airplane', b'automobile', b'bird', b'cat', b'deer', b'dog', b'frog', b'horse', b'ship', b'truck']
b'airplane'


In [ ]:
# for Colab use
data_1 = unpickle('/content/drive/MyDrive/ELEC6604_Sept2022/Class6_7_folder/cifar-10-batches-py/data_batch_1')
for x in data_1:
  print('print x:',x)

print x: b'batch_label'
print x: b'labels'
print x: b'data'
print x: b'filenames'


In [ ]:
# for Colab use
data_1_labels=data_1[b'labels']
print('len(data_1_labels) = ',len(data_1_labels))
#print(data_1_labels)

data_1_data=data_1[b'data']
print('data_1_data.shape = ',data_1_data.shape)
#print(data_1_data)

len(data_1_labels) =  10000
data_1_data.shape =  (10000, 3072)


**Why 3072 ?  How is this calculated ?**

In [ ]:
# for Colab use
data_2 = unpickle('/content/drive/MyDrive/ELEC6604_Sept2022/Class6_7_folder/cifar-10-batches-py/data_batch_2')
data_2_labels=data_2[b'labels']
data_2_data=data_2[b'data']

data_3 = unpickle('/content/drive/MyDrive/ELEC6604_Sept2022/Class6_7_folder/cifar-10-batches-py/data_batch_3')
data_3_labels=data_3[b'labels']
data_3_data=data_3[b'data']

data_4 = unpickle('/content/drive/MyDrive/ELEC6604_Sept2022/Class6_7_folder/cifar-10-batches-py/data_batch_4')
data_4_labels=data_4[b'labels']
data_4_data=data_4[b'data']

data_5 = unpickle('/content/drive/MyDrive/ELEC6604_Sept2022/Class6_7_folder/cifar-10-batches-py/data_batch_5')
data_5_labels=data_5[b'labels']
data_5_data=data_5[b'data']

In [ ]:
# for Colab use
tmp2=np.append(data_1_labels,data_2_labels,axis=0)
tmp2=np.append(tmp2,data_3_labels,axis=0)
tmp2=np.append(tmp2,data_4_labels,axis=0)
y_train=np.append(tmp2,data_5_labels,axis=0)
print('y_train.shape = ',y_train.shape)

y_train.shape =  (50000,)


In [ ]:
# for Colab use
tmp1=np.append(data_1_data,data_2_data,axis=0)
tmp1=np.append(tmp1,data_3_data,axis=0)
tmp1=np.append(tmp1,data_4_data,axis=0)
X_train=np.append(tmp1,data_5_data,axis=0)
print('X_train.shape = ',X_train.shape)

X_train.shape =  (50000, 3072)


In [ ]:
# for Colab use
test_batch = unpickle('/content/drive/MyDrive/ELEC6604_Sept2022/Class6_7_folder/cifar-10-batches-py/test_batch')
y_test=test_batch[b'labels']
X_test=test_batch[b'data']
print('len(y_test) = ',len(y_test))
print('X_test.shape = ',X_test.shape)
print(X_test)

len(y_test) =  10000
X_test.shape =  (10000, 3072)
[[158 159 165 ... 124 129 110]
 [235 231 232 ... 178 191 199]
 [158 158 139 ...   8   3   7]
 ...
 [ 20  19  15 ...  50  53  47]
 [ 25  15  23 ...  80  81  80]
 [ 73  98  99 ...  94  58  26]]


In [ ]:
# for Colab use
# building the input vector from the 32x32 pixels
X_train = X_train.reshape(X_train.shape[0], 32, 32, 3)
X_test = X_test.reshape(X_test.shape[0], 32, 32, 3)

print('X_train.shape is ', X_train.shape)
print('y_train.shape is ', y_train.shape)
print('X_test.shape is ', X_test.shape)
print('len(y_test) = ',len(y_test))

X_train.shape is  (50000, 32, 32, 3)
y_train.shape is  (50000,)
X_test.shape is  (10000, 32, 32, 3)
len(y_test) =  10000


In [12]:
# PART 3: THE FOLLOWING IS THE SAME CODING FOR BOTH COLAB and JUPYTER NOTEBOOK
#

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalizing the data to help with the training
X_train /= 255
X_test /= 255

In [16]:
# PART 4: Investigation on Normalization 

# What is the significance of the following step in this section ?
# Examine whether the step has helped in the training process.
# Basically, you would like to examine whether the training result is affected
# with and without running the following two lines.

X_train = (X_train - 0.5)*2

X_test = (X_test - 0.5)*2


In [18]:
# PART 5: one-hot encoding using keras' numpy-related utilities
n_classes = 10
print("Shape before one-hot encoding: ", y_train.shape)
# Y_train = np_utils.to_categorical(y_train, n_classes)
# Y_test = np_utils.to_categorical(y_test, n_classes)
Y_train = to_categorical(y_train, n_classes)
Y_test = to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)

Shape before one-hot encoding:  (50000, 1)
Shape after one-hot encoding:  (50000, 10)


In [19]:
# Double-check on the dimension

print('X_train.shape is ', X_train.shape)
print('Y_train.shape is ', Y_train.shape)
print('X_test.shape is ', X_test.shape)
print('Y_test.shape is ', Y_test.shape)

X_train.shape is  (50000, 32, 32, 3)
Y_train.shape is  (50000, 10)
X_test.shape is  (10000, 32, 32, 3)
Y_test.shape is  (10000, 10)


In [13]:
# PART 6 : CNN model development
# ......
# ......

In [14]:
# plots (COLAB CODING)

plt.figure(0)
plt.plot(cnn.history['accuracy'],'r')
plt.plot(cnn.history['val_accuracy'],'g')
plt.ylim(0,1)
plt.rcParams['figure.figsize'] = (8, 6)
plt.xlabel("Num of Epochs")
plt.ylabel("accuracy")
plt.title("Training accuracy vs Validation accuracy")
plt.legend(['train','validation'])

plt.figure(1)
plt.plot(cnn.history['loss'],'r')
plt.plot(cnn.history['val_loss'],'g')
plt.ylim(0,2)
plt.rcParams['figure.figsize'] = (8, 6)
plt.xlabel("Num of Epochs")
plt.ylabel("loss")
plt.title("Training loss vs Validation loss")
plt.legend(['train','validation'])

plt.show()

NameError: name 'cnn' is not defined

<Figure size 432x288 with 0 Axes>

In [ ]:
# JUPYTER NOTEBOOK CODING
# Plots for training and testing process: loss and accuracy

plt.figure(0)
plt.plot(cnn.history['acc'],'r')
plt.plot(cnn.history['val_acc'],'g')
plt.xticks(np.arange(0, 101, 2.0))
plt.rcParams['figure.figsize'] = (8, 6)
plt.xlabel("Num of Epochs")
plt.ylabel("Accuracy")
plt.title("Training Accuracy vs Validation Accuracy")
plt.legend(['train','validation'])


plt.figure(1)
plt.plot(cnn.history['loss'],'r')
plt.plot(cnn.history['val_loss'],'g')
plt.xticks(np.arange(0, 101, 2.0))
plt.rcParams['figure.figsize'] = (8, 6)
plt.xlabel("Num of Epochs")
plt.ylabel("Loss")
plt.title("Training Loss vs Validation Loss")
plt.legend(['train','validation'])


plt.show()

KeyError: ignored

<Figure size 432x288 with 0 Axes>